M2kException: Add general exception.
Create a general exception that contains a message, a type and an error
code.
These modifications were added because of the necessity of handling
different situation depending on the iio error code.

Signed-off-by: Teo Perisanu <Teo.Perisanu@analog.com>